# Generated by Django 5.2.8 on 2025-11-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_remove_curso_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='idioma',
            field=models.CharField(default='Español', max_length=20),
            preserve_default=False,
        ),
    ]
