# Generated by Django 5.2.8 on 2025-11-20 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_curso_idioma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nombre',
        ),
    ]
