# Generated by Django 5.2.8 on 2025-11-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_remove_curso_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=30)),
                ('cursos', models.ManyToManyField(blank=True, to='curso.curso')),
            ],
        ),
    ]
