# Generated by Django 5.2.8 on 2025-11-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_alumno_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
