# Generated by Django 5.2.8 on 2025-11-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_curso_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profesores/'),
        ),
    ]
