# Generated by Django 5.2.8 on 2025-11-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_alumno_imagen_profesor_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='imagen',
        ),
    ]
